
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const AutoComplete: typeof import("primevue/autocomplete")['default']
export const CascadeSelect: typeof import("primevue/cascadeselect")['default']
export const Checkbox: typeof import("primevue/checkbox")['default']
export const CheckboxGroup: typeof import("primevue/checkboxgroup")['default']
export const ColorPicker: typeof import("primevue/colorpicker")['default']
export const DatePicker: typeof import("primevue/datepicker")['default']
export const FloatLabel: typeof import("primevue/floatlabel")['default']
export const Fluid: typeof import("primevue/fluid")['default']
export const IconField: typeof import("primevue/iconfield")['default']
export const IftaLabel: typeof import("primevue/iftalabel")['default']
export const InputColor: typeof import("primevue/inputcolor")['default']
export const InputColorArea: typeof import("primevue/inputcolorarea")['default']
export const InputColorAreaBackground: typeof import("primevue/inputcolorareabackground")['default']
export const InputColorAreaHandle: typeof import("primevue/inputcolorareahandle")['default']
export const InputColorEyeDropper: typeof import("primevue/inputcoloreyedropper")['default']
export const InputColorInput: typeof import("primevue/inputcolorinput")['default']
export const InputColorSlider: typeof import("primevue/inputcolorslider")['default']
export const InputColorSliderHandle: typeof import("primevue/inputcolorsliderhandle")['default']
export const InputColorSliderTrack: typeof import("primevue/inputcolorslidertrack")['default']
export const InputColorSwatch: typeof import("primevue/inputcolorswatch")['default']
export const InputColorSwatchBackground: typeof import("primevue/inputcolorswatchbackground")['default']
export const InputColorTransparencyGrid: typeof import("primevue/inputcolortransparencygrid")['default']
export const InputGroup: typeof import("primevue/inputgroup")['default']
export const InputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const InputIcon: typeof import("primevue/inputicon")['default']
export const InputMask: typeof import("primevue/inputmask")['default']
export const InputNumber: typeof import("primevue/inputnumber")['default']
export const InputOtp: typeof import("primevue/inputotp")['default']
export const InputPassword: typeof import("primevue/inputpassword")['default']
export const InputTags: typeof import("primevue/inputtags")['default']
export const InputText: typeof import("primevue/inputtext")['default']
export const Knob: typeof import("primevue/knob")['default']
export const Label: typeof import("primevue/label")['default']
export const Listbox: typeof import("primevue/listbox")['default']
export const MultiSelect: typeof import("primevue/multiselect")['default']
export const Password: typeof import("primevue/password")['default']
export const RadioButton: typeof import("primevue/radiobutton")['default']
export const RadioButtonGroup: typeof import("primevue/radiobuttongroup")['default']
export const Rating: typeof import("primevue/rating")['default']
export const Select: typeof import("primevue/select")['default']
export const SelectButton: typeof import("primevue/selectbutton")['default']
export const Slider: typeof import("primevue/slider")['default']
export const Textarea: typeof import("primevue/textarea")['default']
export const ToggleButton: typeof import("primevue/togglebutton")['default']
export const ToggleSwitch: typeof import("primevue/toggleswitch")['default']
export const TreeSelect: typeof import("primevue/treeselect")['default']
export const Button: typeof import("primevue/button")['default']
export const ButtonGroup: typeof import("primevue/buttongroup")['default']
export const SpeedDial: typeof import("primevue/speeddial")['default']
export const SplitButton: typeof import("primevue/splitbutton")['default']
export const Column: typeof import("primevue/column")['default']
export const Row: typeof import("primevue/row")['default']
export const ColumnGroup: typeof import("primevue/columngroup")['default']
export const DataTable: typeof import("primevue/datatable")['default']
export const DataView: typeof import("primevue/dataview")['default']
export const OrderList: typeof import("primevue/orderlist")['default']
export const OrganizationChart: typeof import("primevue/organizationchart")['default']
export const Paginator: typeof import("primevue/paginator")['default']
export const PickList: typeof import("primevue/picklist")['default']
export const Tree: typeof import("primevue/tree")['default']
export const TreeTable: typeof import("primevue/treetable")['default']
export const Timeline: typeof import("primevue/timeline")['default']
export const VirtualScroller: typeof import("primevue/virtualscroller")['default']
export const Accordion: typeof import("primevue/accordion")['default']
export const AccordionPanel: typeof import("primevue/accordionpanel")['default']
export const AccordionHeader: typeof import("primevue/accordionheader")['default']
export const AccordionContent: typeof import("primevue/accordioncontent")['default']
export const Card: typeof import("primevue/card")['default']
export const DeferredContent: typeof import("primevue/deferredcontent")['default']
export const Divider: typeof import("primevue/divider")['default']
export const Fieldset: typeof import("primevue/fieldset")['default']
export const Panel: typeof import("primevue/panel")['default']
export const ScrollArea: typeof import("primevue/scrollarea")['default']
export const ScrollAreaContent: typeof import("primevue/scrollareacontent")['default']
export const ScrollAreaCorner: typeof import("primevue/scrollareacorner")['default']
export const ScrollAreaHandle: typeof import("primevue/scrollareahandle")['default']
export const ScrollAreaScrollbar: typeof import("primevue/scrollareascrollbar")['default']
export const ScrollAreaViewport: typeof import("primevue/scrollareaviewport")['default']
export const ScrollPanel: typeof import("primevue/scrollpanel")['default']
export const Splitter: typeof import("primevue/splitter")['default']
export const SplitterPanel: typeof import("primevue/splitterpanel")['default']
export const Stepper: typeof import("primevue/stepper")['default']
export const StepList: typeof import("primevue/steplist")['default']
export const Step: typeof import("primevue/step")['default']
export const StepItem: typeof import("primevue/stepitem")['default']
export const StepPanels: typeof import("primevue/steppanels")['default']
export const StepPanel: typeof import("primevue/steppanel")['default']
export const Tabs: typeof import("primevue/tabs")['default']
export const TabList: typeof import("primevue/tablist")['default']
export const Tab: typeof import("primevue/tab")['default']
export const TabPanels: typeof import("primevue/tabpanels")['default']
export const TabPanel: typeof import("primevue/tabpanel")['default']
export const Toolbar: typeof import("primevue/toolbar")['default']
export const ConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const ConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const Dialog: typeof import("primevue/dialog")['default']
export const Drawer: typeof import("primevue/drawer")['default']
export const DynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const Popover: typeof import("primevue/popover")['default']
export const FileUpload: typeof import("primevue/fileupload")['default']
export const Breadcrumb: typeof import("primevue/breadcrumb")['default']
export const CommandMenu: typeof import("primevue/commandmenu")['default']
export const ContextMenu: typeof import("primevue/contextmenu")['default']
export const Dock: typeof import("primevue/dock")['default']
export const Menu: typeof import("primevue/menu")['default']
export const Menubar: typeof import("primevue/menubar")['default']
export const MegaMenu: typeof import("primevue/megamenu")['default']
export const PanelMenu: typeof import("primevue/panelmenu")['default']
export const Sidebar: typeof import("primevue/sidebar")['default']
export const SidebarAside: typeof import("primevue/sidebaraside")['default']
export const SidebarBackdrop: typeof import("primevue/sidebarbackdrop")['default']
export const SidebarContent: typeof import("primevue/sidebarcontent")['default']
export const SidebarFooter: typeof import("primevue/sidebarfooter")['default']
export const SidebarGroup: typeof import("primevue/sidebargroup")['default']
export const SidebarGroupAction: typeof import("primevue/sidebargroupaction")['default']
export const SidebarGroupContent: typeof import("primevue/sidebargroupcontent")['default']
export const SidebarGroupLabel: typeof import("primevue/sidebargrouplabel")['default']
export const SidebarHeader: typeof import("primevue/sidebarheader")['default']
export const SidebarLayout: typeof import("primevue/sidebarlayout")['default']
export const SidebarMain: typeof import("primevue/sidebarmain")['default']
export const SidebarMenu: typeof import("primevue/sidebarmenu")['default']
export const SidebarMenuAction: typeof import("primevue/sidebarmenuaction")['default']
export const SidebarMenuBadge: typeof import("primevue/sidebarmenubadge")['default']
export const SidebarMenuButton: typeof import("primevue/sidebarmenubutton")['default']
export const SidebarMenuItem: typeof import("primevue/sidebarmenuitem")['default']
export const SidebarMenuSub: typeof import("primevue/sidebarmenusub")['default']
export const SidebarMenuSubButton: typeof import("primevue/sidebarmenusubbutton")['default']
export const SidebarMenuSubItem: typeof import("primevue/sidebarmenusubitem")['default']
export const SidebarPanel: typeof import("primevue/sidebarpanel")['default']
export const SidebarRail: typeof import("primevue/sidebarrail")['default']
export const SidebarSpacer: typeof import("primevue/sidebarspacer")['default']
export const SidebarTrigger: typeof import("primevue/sidebartrigger")['default']
export const Steps: typeof import("primevue/steps")['default']
export const TieredMenu: typeof import("primevue/tieredmenu")['default']
export const Message: typeof import("primevue/message")['default']
export const Toast: typeof import("primevue/toast")['default']
export const Carousel: typeof import("primevue/carousel")['default']
export const CarouselContent: typeof import("primevue/carouselcontent")['default']
export const CarouselIndicator: typeof import("primevue/carouselindicator")['default']
export const CarouselIndicators: typeof import("primevue/carouselindicators")['default']
export const CarouselItem: typeof import("primevue/carouselitem")['default']
export const CarouselNext: typeof import("primevue/carouselnext")['default']
export const CarouselPrev: typeof import("primevue/carouselprev")['default']
export const Galleria: typeof import("primevue/galleria")['default']
export const Gallery: typeof import("primevue/gallery")['default']
export const GalleryBackdrop: typeof import("primevue/gallerybackdrop")['default']
export const GalleryContent: typeof import("primevue/gallerycontent")['default']
export const GalleryDownload: typeof import("primevue/gallerydownload")['default']
export const GalleryFlipX: typeof import("primevue/galleryflipx")['default']
export const GalleryFlipY: typeof import("primevue/galleryflipy")['default']
export const GalleryFooter: typeof import("primevue/galleryfooter")['default']
export const GalleryFullScreen: typeof import("primevue/galleryfullscreen")['default']
export const GalleryHeader: typeof import("primevue/galleryheader")['default']
export const GalleryItem: typeof import("primevue/galleryitem")['default']
export const GalleryNext: typeof import("primevue/gallerynext")['default']
export const GalleryPrev: typeof import("primevue/galleryprev")['default']
export const GalleryRotateLeft: typeof import("primevue/galleryrotateleft")['default']
export const GalleryRotateRight: typeof import("primevue/galleryrotateright")['default']
export const GalleryThumbnail: typeof import("primevue/gallerythumbnail")['default']
export const GalleryThumbnailContent: typeof import("primevue/gallerythumbnailcontent")['default']
export const GalleryThumbnailItem: typeof import("primevue/gallerythumbnailitem")['default']
export const GalleryZoomIn: typeof import("primevue/galleryzoomin")['default']
export const GalleryZoomOut: typeof import("primevue/galleryzoomout")['default']
export const GalleryZoomToggle: typeof import("primevue/galleryzoomtoggle")['default']
export const Compare: typeof import("primevue/compare")['default']
export const CompareHandle: typeof import("primevue/comparehandle")['default']
export const CompareIndicator: typeof import("primevue/compareindicator")['default']
export const CompareItem: typeof import("primevue/compareitem")['default']
export const Image: typeof import("primevue/image")['default']
export const ImageCompare: typeof import("primevue/imagecompare")['default']
export const Avatar: typeof import("primevue/avatar")['default']
export const AvatarGroup: typeof import("primevue/avatargroup")['default']
export const Badge: typeof import("primevue/badge")['default']
export const BlockUI: typeof import("primevue/blockui")['default']
export const Chip: typeof import("primevue/chip")['default']
export const Inplace: typeof import("primevue/inplace")['default']
export const MeterGroup: typeof import("primevue/metergroup")['default']
export const OverlayBadge: typeof import("primevue/overlaybadge")['default']
export const ScrollTop: typeof import("primevue/scrolltop")['default']
export const Skeleton: typeof import("primevue/skeleton")['default']
export const ProgressBar: typeof import("primevue/progressbar")['default']
export const ProgressSpinner: typeof import("primevue/progressspinner")['default']
export const Tag: typeof import("primevue/tag")['default']
export const Terminal: typeof import("primevue/terminal")['default']
export const Form: typeof import("@primevue/forms/form")['default']
export const FormField: typeof import("@primevue/forms/formfield")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyAutoComplete: LazyComponent<typeof import("primevue/autocomplete")['default']>
export const LazyCascadeSelect: LazyComponent<typeof import("primevue/cascadeselect")['default']>
export const LazyCheckbox: LazyComponent<typeof import("primevue/checkbox")['default']>
export const LazyCheckboxGroup: LazyComponent<typeof import("primevue/checkboxgroup")['default']>
export const LazyColorPicker: LazyComponent<typeof import("primevue/colorpicker")['default']>
export const LazyDatePicker: LazyComponent<typeof import("primevue/datepicker")['default']>
export const LazyFloatLabel: LazyComponent<typeof import("primevue/floatlabel")['default']>
export const LazyFluid: LazyComponent<typeof import("primevue/fluid")['default']>
export const LazyIconField: LazyComponent<typeof import("primevue/iconfield")['default']>
export const LazyIftaLabel: LazyComponent<typeof import("primevue/iftalabel")['default']>
export const LazyInputColor: LazyComponent<typeof import("primevue/inputcolor")['default']>
export const LazyInputColorArea: LazyComponent<typeof import("primevue/inputcolorarea")['default']>
export const LazyInputColorAreaBackground: LazyComponent<typeof import("primevue/inputcolorareabackground")['default']>
export const LazyInputColorAreaHandle: LazyComponent<typeof import("primevue/inputcolorareahandle")['default']>
export const LazyInputColorEyeDropper: LazyComponent<typeof import("primevue/inputcoloreyedropper")['default']>
export const LazyInputColorInput: LazyComponent<typeof import("primevue/inputcolorinput")['default']>
export const LazyInputColorSlider: LazyComponent<typeof import("primevue/inputcolorslider")['default']>
export const LazyInputColorSliderHandle: LazyComponent<typeof import("primevue/inputcolorsliderhandle")['default']>
export const LazyInputColorSliderTrack: LazyComponent<typeof import("primevue/inputcolorslidertrack")['default']>
export const LazyInputColorSwatch: LazyComponent<typeof import("primevue/inputcolorswatch")['default']>
export const LazyInputColorSwatchBackground: LazyComponent<typeof import("primevue/inputcolorswatchbackground")['default']>
export const LazyInputColorTransparencyGrid: LazyComponent<typeof import("primevue/inputcolortransparencygrid")['default']>
export const LazyInputGroup: LazyComponent<typeof import("primevue/inputgroup")['default']>
export const LazyInputGroupAddon: LazyComponent<typeof import("primevue/inputgroupaddon")['default']>
export const LazyInputIcon: LazyComponent<typeof import("primevue/inputicon")['default']>
export const LazyInputMask: LazyComponent<typeof import("primevue/inputmask")['default']>
export const LazyInputNumber: LazyComponent<typeof import("primevue/inputnumber")['default']>
export const LazyInputOtp: LazyComponent<typeof import("primevue/inputotp")['default']>
export const LazyInputPassword: LazyComponent<typeof import("primevue/inputpassword")['default']>
export const LazyInputTags: LazyComponent<typeof import("primevue/inputtags")['default']>
export const LazyInputText: LazyComponent<typeof import("primevue/inputtext")['default']>
export const LazyKnob: LazyComponent<typeof import("primevue/knob")['default']>
export const LazyLabel: LazyComponent<typeof import("primevue/label")['default']>
export const LazyListbox: LazyComponent<typeof import("primevue/listbox")['default']>
export const LazyMultiSelect: LazyComponent<typeof import("primevue/multiselect")['default']>
export const LazyPassword: LazyComponent<typeof import("primevue/password")['default']>
export const LazyRadioButton: LazyComponent<typeof import("primevue/radiobutton")['default']>
export const LazyRadioButtonGroup: LazyComponent<typeof import("primevue/radiobuttongroup")['default']>
export const LazyRating: LazyComponent<typeof import("primevue/rating")['default']>
export const LazySelect: LazyComponent<typeof import("primevue/select")['default']>
export const LazySelectButton: LazyComponent<typeof import("primevue/selectbutton")['default']>
export const LazySlider: LazyComponent<typeof import("primevue/slider")['default']>
export const LazyTextarea: LazyComponent<typeof import("primevue/textarea")['default']>
export const LazyToggleButton: LazyComponent<typeof import("primevue/togglebutton")['default']>
export const LazyToggleSwitch: LazyComponent<typeof import("primevue/toggleswitch")['default']>
export const LazyTreeSelect: LazyComponent<typeof import("primevue/treeselect")['default']>
export const LazyButton: LazyComponent<typeof import("primevue/button")['default']>
export const LazyButtonGroup: LazyComponent<typeof import("primevue/buttongroup")['default']>
export const LazySpeedDial: LazyComponent<typeof import("primevue/speeddial")['default']>
export const LazySplitButton: LazyComponent<typeof import("primevue/splitbutton")['default']>
export const LazyColumn: LazyComponent<typeof import("primevue/column")['default']>
export const LazyRow: LazyComponent<typeof import("primevue/row")['default']>
export const LazyColumnGroup: LazyComponent<typeof import("primevue/columngroup")['default']>
export const LazyDataTable: LazyComponent<typeof import("primevue/datatable")['default']>
export const LazyDataView: LazyComponent<typeof import("primevue/dataview")['default']>
export const LazyOrderList: LazyComponent<typeof import("primevue/orderlist")['default']>
export const LazyOrganizationChart: LazyComponent<typeof import("primevue/organizationchart")['default']>
export const LazyPaginator: LazyComponent<typeof import("primevue/paginator")['default']>
export const LazyPickList: LazyComponent<typeof import("primevue/picklist")['default']>
export const LazyTree: LazyComponent<typeof import("primevue/tree")['default']>
export const LazyTreeTable: LazyComponent<typeof import("primevue/treetable")['default']>
export const LazyTimeline: LazyComponent<typeof import("primevue/timeline")['default']>
export const LazyVirtualScroller: LazyComponent<typeof import("primevue/virtualscroller")['default']>
export const LazyAccordion: LazyComponent<typeof import("primevue/accordion")['default']>
export const LazyAccordionPanel: LazyComponent<typeof import("primevue/accordionpanel")['default']>
export const LazyAccordionHeader: LazyComponent<typeof import("primevue/accordionheader")['default']>
export const LazyAccordionContent: LazyComponent<typeof import("primevue/accordioncontent")['default']>
export const LazyCard: LazyComponent<typeof import("primevue/card")['default']>
export const LazyDeferredContent: LazyComponent<typeof import("primevue/deferredcontent")['default']>
export const LazyDivider: LazyComponent<typeof import("primevue/divider")['default']>
export const LazyFieldset: LazyComponent<typeof import("primevue/fieldset")['default']>
export const LazyPanel: LazyComponent<typeof import("primevue/panel")['default']>
export const LazyScrollArea: LazyComponent<typeof import("primevue/scrollarea")['default']>
export const LazyScrollAreaContent: LazyComponent<typeof import("primevue/scrollareacontent")['default']>
export const LazyScrollAreaCorner: LazyComponent<typeof import("primevue/scrollareacorner")['default']>
export const LazyScrollAreaHandle: LazyComponent<typeof import("primevue/scrollareahandle")['default']>
export const LazyScrollAreaScrollbar: LazyComponent<typeof import("primevue/scrollareascrollbar")['default']>
export const LazyScrollAreaViewport: LazyComponent<typeof import("primevue/scrollareaviewport")['default']>
export const LazyScrollPanel: LazyComponent<typeof import("primevue/scrollpanel")['default']>
export const LazySplitter: LazyComponent<typeof import("primevue/splitter")['default']>
export const LazySplitterPanel: LazyComponent<typeof import("primevue/splitterpanel")['default']>
export const LazyStepper: LazyComponent<typeof import("primevue/stepper")['default']>
export const LazyStepList: LazyComponent<typeof import("primevue/steplist")['default']>
export const LazyStep: LazyComponent<typeof import("primevue/step")['default']>
export const LazyStepItem: LazyComponent<typeof import("primevue/stepitem")['default']>
export const LazyStepPanels: LazyComponent<typeof import("primevue/steppanels")['default']>
export const LazyStepPanel: LazyComponent<typeof import("primevue/steppanel")['default']>
export const LazyTabs: LazyComponent<typeof import("primevue/tabs")['default']>
export const LazyTabList: LazyComponent<typeof import("primevue/tablist")['default']>
export const LazyTab: LazyComponent<typeof import("primevue/tab")['default']>
export const LazyTabPanels: LazyComponent<typeof import("primevue/tabpanels")['default']>
export const LazyTabPanel: LazyComponent<typeof import("primevue/tabpanel")['default']>
export const LazyToolbar: LazyComponent<typeof import("primevue/toolbar")['default']>
export const LazyConfirmDialog: LazyComponent<typeof import("primevue/confirmdialog")['default']>
export const LazyConfirmPopup: LazyComponent<typeof import("primevue/confirmpopup")['default']>
export const LazyDialog: LazyComponent<typeof import("primevue/dialog")['default']>
export const LazyDrawer: LazyComponent<typeof import("primevue/drawer")['default']>
export const LazyDynamicDialog: LazyComponent<typeof import("primevue/dynamicdialog")['default']>
export const LazyPopover: LazyComponent<typeof import("primevue/popover")['default']>
export const LazyFileUpload: LazyComponent<typeof import("primevue/fileupload")['default']>
export const LazyBreadcrumb: LazyComponent<typeof import("primevue/breadcrumb")['default']>
export const LazyCommandMenu: LazyComponent<typeof import("primevue/commandmenu")['default']>
export const LazyContextMenu: LazyComponent<typeof import("primevue/contextmenu")['default']>
export const LazyDock: LazyComponent<typeof import("primevue/dock")['default']>
export const LazyMenu: LazyComponent<typeof import("primevue/menu")['default']>
export const LazyMenubar: LazyComponent<typeof import("primevue/menubar")['default']>
export const LazyMegaMenu: LazyComponent<typeof import("primevue/megamenu")['default']>
export const LazyPanelMenu: LazyComponent<typeof import("primevue/panelmenu")['default']>
export const LazySidebar: LazyComponent<typeof import("primevue/sidebar")['default']>
export const LazySidebarAside: LazyComponent<typeof import("primevue/sidebaraside")['default']>
export const LazySidebarBackdrop: LazyComponent<typeof import("primevue/sidebarbackdrop")['default']>
export const LazySidebarContent: LazyComponent<typeof import("primevue/sidebarcontent")['default']>
export const LazySidebarFooter: LazyComponent<typeof import("primevue/sidebarfooter")['default']>
export const LazySidebarGroup: LazyComponent<typeof import("primevue/sidebargroup")['default']>
export const LazySidebarGroupAction: LazyComponent<typeof import("primevue/sidebargroupaction")['default']>
export const LazySidebarGroupContent: LazyComponent<typeof import("primevue/sidebargroupcontent")['default']>
export const LazySidebarGroupLabel: LazyComponent<typeof import("primevue/sidebargrouplabel")['default']>
export const LazySidebarHeader: LazyComponent<typeof import("primevue/sidebarheader")['default']>
export const LazySidebarLayout: LazyComponent<typeof import("primevue/sidebarlayout")['default']>
export const LazySidebarMain: LazyComponent<typeof import("primevue/sidebarmain")['default']>
export const LazySidebarMenu: LazyComponent<typeof import("primevue/sidebarmenu")['default']>
export const LazySidebarMenuAction: LazyComponent<typeof import("primevue/sidebarmenuaction")['default']>
export const LazySidebarMenuBadge: LazyComponent<typeof import("primevue/sidebarmenubadge")['default']>
export const LazySidebarMenuButton: LazyComponent<typeof import("primevue/sidebarmenubutton")['default']>
export const LazySidebarMenuItem: LazyComponent<typeof import("primevue/sidebarmenuitem")['default']>
export const LazySidebarMenuSub: LazyComponent<typeof import("primevue/sidebarmenusub")['default']>
export const LazySidebarMenuSubButton: LazyComponent<typeof import("primevue/sidebarmenusubbutton")['default']>
export const LazySidebarMenuSubItem: LazyComponent<typeof import("primevue/sidebarmenusubitem")['default']>
export const LazySidebarPanel: LazyComponent<typeof import("primevue/sidebarpanel")['default']>
export const LazySidebarRail: LazyComponent<typeof import("primevue/sidebarrail")['default']>
export const LazySidebarSpacer: LazyComponent<typeof import("primevue/sidebarspacer")['default']>
export const LazySidebarTrigger: LazyComponent<typeof import("primevue/sidebartrigger")['default']>
export const LazySteps: LazyComponent<typeof import("primevue/steps")['default']>
export const LazyTieredMenu: LazyComponent<typeof import("primevue/tieredmenu")['default']>
export const LazyMessage: LazyComponent<typeof import("primevue/message")['default']>
export const LazyToast: LazyComponent<typeof import("primevue/toast")['default']>
export const LazyCarousel: LazyComponent<typeof import("primevue/carousel")['default']>
export const LazyCarouselContent: LazyComponent<typeof import("primevue/carouselcontent")['default']>
export const LazyCarouselIndicator: LazyComponent<typeof import("primevue/carouselindicator")['default']>
export const LazyCarouselIndicators: LazyComponent<typeof import("primevue/carouselindicators")['default']>
export const LazyCarouselItem: LazyComponent<typeof import("primevue/carouselitem")['default']>
export const LazyCarouselNext: LazyComponent<typeof import("primevue/carouselnext")['default']>
export const LazyCarouselPrev: LazyComponent<typeof import("primevue/carouselprev")['default']>
export const LazyGalleria: LazyComponent<typeof import("primevue/galleria")['default']>
export const LazyGallery: LazyComponent<typeof import("primevue/gallery")['default']>
export const LazyGalleryBackdrop: LazyComponent<typeof import("primevue/gallerybackdrop")['default']>
export const LazyGalleryContent: LazyComponent<typeof import("primevue/gallerycontent")['default']>
export const LazyGalleryDownload: LazyComponent<typeof import("primevue/gallerydownload")['default']>
export const LazyGalleryFlipX: LazyComponent<typeof import("primevue/galleryflipx")['default']>
export const LazyGalleryFlipY: LazyComponent<typeof import("primevue/galleryflipy")['default']>
export const LazyGalleryFooter: LazyComponent<typeof import("primevue/galleryfooter")['default']>
export const LazyGalleryFullScreen: LazyComponent<typeof import("primevue/galleryfullscreen")['default']>
export const LazyGalleryHeader: LazyComponent<typeof import("primevue/galleryheader")['default']>
export const LazyGalleryItem: LazyComponent<typeof import("primevue/galleryitem")['default']>
export const LazyGalleryNext: LazyComponent<typeof import("primevue/gallerynext")['default']>
export const LazyGalleryPrev: LazyComponent<typeof import("primevue/galleryprev")['default']>
export const LazyGalleryRotateLeft: LazyComponent<typeof import("primevue/galleryrotateleft")['default']>
export const LazyGalleryRotateRight: LazyComponent<typeof import("primevue/galleryrotateright")['default']>
export const LazyGalleryThumbnail: LazyComponent<typeof import("primevue/gallerythumbnail")['default']>
export const LazyGalleryThumbnailContent: LazyComponent<typeof import("primevue/gallerythumbnailcontent")['default']>
export const LazyGalleryThumbnailItem: LazyComponent<typeof import("primevue/gallerythumbnailitem")['default']>
export const LazyGalleryZoomIn: LazyComponent<typeof import("primevue/galleryzoomin")['default']>
export const LazyGalleryZoomOut: LazyComponent<typeof import("primevue/galleryzoomout")['default']>
export const LazyGalleryZoomToggle: LazyComponent<typeof import("primevue/galleryzoomtoggle")['default']>
export const LazyCompare: LazyComponent<typeof import("primevue/compare")['default']>
export const LazyCompareHandle: LazyComponent<typeof import("primevue/comparehandle")['default']>
export const LazyCompareIndicator: LazyComponent<typeof import("primevue/compareindicator")['default']>
export const LazyCompareItem: LazyComponent<typeof import("primevue/compareitem")['default']>
export const LazyImage: LazyComponent<typeof import("primevue/image")['default']>
export const LazyImageCompare: LazyComponent<typeof import("primevue/imagecompare")['default']>
export const LazyAvatar: LazyComponent<typeof import("primevue/avatar")['default']>
export const LazyAvatarGroup: LazyComponent<typeof import("primevue/avatargroup")['default']>
export const LazyBadge: LazyComponent<typeof import("primevue/badge")['default']>
export const LazyBlockUI: LazyComponent<typeof import("primevue/blockui")['default']>
export const LazyChip: LazyComponent<typeof import("primevue/chip")['default']>
export const LazyInplace: LazyComponent<typeof import("primevue/inplace")['default']>
export const LazyMeterGroup: LazyComponent<typeof import("primevue/metergroup")['default']>
export const LazyOverlayBadge: LazyComponent<typeof import("primevue/overlaybadge")['default']>
export const LazyScrollTop: LazyComponent<typeof import("primevue/scrolltop")['default']>
export const LazySkeleton: LazyComponent<typeof import("primevue/skeleton")['default']>
export const LazyProgressBar: LazyComponent<typeof import("primevue/progressbar")['default']>
export const LazyProgressSpinner: LazyComponent<typeof import("primevue/progressspinner")['default']>
export const LazyTag: LazyComponent<typeof import("primevue/tag")['default']>
export const LazyTerminal: LazyComponent<typeof import("primevue/terminal")['default']>
export const LazyForm: LazyComponent<typeof import("@primevue/forms/form")['default']>
export const LazyFormField: LazyComponent<typeof import("@primevue/forms/formfield")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
